#!/bin/bash

: ${FLY_TARGET?"Need the fly target FLY_TARGET"}
: ${CONCOURSE_URL?"Need the concourse url"}

export CONCOURSE_URL=${$(echo "https://${CONCOURSE_URL#https://}")%/}

login_concourse() {
  local concourse_password=$(lpass show --note 'concourse-chorebot-secrets.yml' | grep concourse_admin_password | awk '{print $2}')

  fly -t "$FLY_TARGET" login -c "$CONCOURSE_URL" -u admin -p "$concourse_password"
}

open_pipeline() {
  local pipeline_name=${1?}
  local pipeline_url="${CONCOURSE_URL}/teams/main/pipelines/${pipeline_name}"

  echo "Open $pipeline_url"
  open "$pipeline_url"
}

open_cleanup_pipeline() {
  local lock_name=${1?"Need the lock name"}
  local pipeline_name=${2:-"all-envs-maintenance-master"}
  local cleanup_job_name="cleanup-$lock_name"
  local pipeline_url=""
  local build_info=$(get_recent_build $pipeline_name $cleanup_job_name)

  if [ -n "$build_info" ]; then
    echo "$build_info"
    build_num=$(echo $build_info | awk '{print $3}')
    pipeline_url="${CONCOURSE_URL}/teams/main/pipelines/${pipeline_name}/jobs/${cleanup_job_name}/builds/${build_num}"
  else
    pipeline_url="${CONCOURSE_URL}/teams/main/pipelines/${pipeline_name}/jobs/${cleanup_job_name}"
  fi

  echo "Open $pipeline_url"
  open "$pipeline_url"
}

flyhijack() {
  local build_url=${1?}

  fly -t "$FLY_TARGET" hijack -u "$build_url"
}

cleanup_lock() {
  local lock_name=${1?"Need the lock name"}
  local pipeline_name=${2:-"all-envs-maintenance-master"}

  fly -t "$FLY_TARGET" trigger-job -j "${pipeline_name}/cleanup-${lock_name}"
}

get_recent_build() {
  local pipeline_name=${1?"Need the pipeline name"}
  local job_name=${2?"Need the job name"}
  local build_count=${3:-1}

  fly -t "$FLY_TARGET" builds -j ${pipeline_name}/${job_name} -c "$build_count"
}
